name: Build .NET Project with Attestation

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write         # ✅ Required for attestation
  contents: read          # ✅ Required to read repo contents
  security-events: write  # ✅ Required to persist attestation
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore HelloWorldApp/HelloWorldApp.csproj

    - name: Build Project
      run: dotnet build HelloWorldApp/HelloWorldApp.csproj --configuration Release

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorldApp
        path: HelloWorldApp/bin/Release/net8.0/

    # ✅ Attestation for Build Provenance (SLSA)
    - name: Generate Build Attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: HelloWorldApp/bin/Release/net8.0/
